openapi: 3.0.3
info:
  version: 5.13.0
  title: Pinterest Multiple API
  description: This is the description of your API.
  contact:
    name: Pinterest, Inc.
    url: https://developers.pinterest.com/
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://developers.pinterest.com/terms/
servers:
- url: https://api.pinterest.com/v5
tags:
- name: Multiple
paths:
  /catalogs/product_groups/multiple:
    delete:
      x-ratelimit-category: catalogs_write
      summary: Delete multiple product groups
      description: 'Delete product groups owned by the "operation user_account".

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href=''/docs/api/v5/#operation/ad_accounts/list''>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.


        <a href=''/docs/shopping/catalog/''>Learn more</a>'
      operationId: catalogs_product_groups/delete_many
      x-sandbox: enabled
      parameters:
      - $ref: '#/components/parameters/query_catalogs_product_group_ids_required'
      - $ref: '#/components/parameters/query_ad_account_id'
      security:
      - pinterest_oauth2:
        - catalogs:write
      responses:
        '204':
          description: Catalogs Product Groups deleted successfully.
        '401':
          description: Unauthorized access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                UnauthorizedAccess:
                  value:
                    code: 29
                    message: You are not permitted to access that resource.
        '403':
          description: Forbidden. Account not approved for catalog product group mutations yet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MerchantDisapproved:
                  value:
                    code: 2625
                    message: Sorry, you cannot perform this action. Account is disapproved.
                MerchantUnderReview:
                  value:
                    code: 2626
                    message: Sorry, you cannot perform this action. Account is under review.
        '404':
          description: Catalogs product group not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                CatalogsProductGroupNotFound:
                  value:
                    code: 4180
                    message: Sorry! We could not find your catalogs product group.
        '409':
          description: Conflict. Can't delete this catalogs product group.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                CatalogsProductGroupHasActivePromotions:
                  value:
                    code: 4176
                    message: We can't delete a Catalogs Product Group with active promotions.
                CannotAlterAutoGeneratedCatalogsProductGroup:
                  value:
                    code: 4177
                    message: You cannot alter an auto generated catalogs product group.
                CatalogsMerchantNotCreated:
                  value:
                    code: 4182
                    message: Can't access this feature without an existing catalog.
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
      - Multiple
    post:
      x-ratelimit-category: catalogs_write
      summary: Create multiple product group
      description: 'Create product group to use in Catalogs owned by the "operation user_account".

        - By default, the "operation user_account" is the token user_account.


        Optional: Business Access: Specify an <code>ad_account_id</code> (obtained via <a href=''/docs/api/v5/#operation/ad_accounts/list''>List ad accounts</a>) to use the owner of that ad_account as the "operation user_account". In order to do this, the token user_account must have one of the following <a href="https://help.pinterest.com/en/business/article/share-and-manage-access-to-your-ad-accounts">Business Access</a> roles on the ad_account: Owner, Admin, Catalogs Manager.


        <a href=''/docs/shopping/catalog/''>Learn more</a>


        Note: The catalog type of Creative Assets is only allowed in the <a href=''https://api-sandbox.pinterest.com/v5''>Pinterest API Sandbox</a>.

        If access is required, please contact your partner manager.'
      operationId: catalogs_product_groups/create_many
      security:
      - pinterest_oauth2:
        - catalogs:write
      x-sandbox: enabled
      parameters:
      - $ref: '#/components/parameters/query_ad_account_id'
      requestBody:
        description: Request object used to create one or more catalogs product groups.
        required: true
        content:
          application/json:
            schema:
              type: array
              title: multiple product groups
              items:
                oneOf:
                - $ref: '#/components/schemas/CatalogsProductGroupCreateRequest'
                - $ref: '#/components/schemas/CatalogsVerticalProductGroupCreateRequest'
            examples:
              RetailFewFiltersUsingAllOf:
                summary: A simple retail example that applies "all of the following filters".
                description: 'The use of "all_of" creates a Product Group where all of the individual filters

                  must be satisfied by a product to be included in the Product Group.

                  '
                value:
                - name: Few Filters using "all_of"
                  feed_id: '2680059592705'
                  featured: false
                  filters:
                    all_of:
                    - MIN_PRICE:
                        values: 999.99
                        inclusion: true
                    - CURRENCY:
                        values: USD
                    - CUSTOM_LABEL_0:
                        values:
                        - Luxury Items
              RetailManyFiltersUsingAnyOf:
                summary: A more complete retail example that applies "any of the following filters".
                description: 'The use of "any_of" creates a Product Group where any of the individual filters

                  can add products to the Product Group independently.

                  '
                value:
                - name: Many Filters using "any_of"
                  featured: false
                  feed_id: '2680059592705'
                  filters:
                    all_of:
                    - MIN_PRICE:
                        values: 111.55
                        inclusion: false
                        negated: false
                    - CURRENCY:
                        values: USD
                        negated: false
                    - AVAILABILITY:
                        values:
                        - IN_STOCK
                        - OUT_OF_STOCK
                        - PREORDER
                        negated: false
                    - BRAND:
                        values:
                        - avanti
                        - beautyrest
                        negated: true
                    - GOOGLE_PRODUCT_CATEGORY_0:
                        values:
                        - - furniture
                          - tables
                          - accent tables
                          - end tables
                        - - furniture
                          - chairs
                          - slipper chairs
                        - - home & garden
                        negated: false
                    - CONDITION:
                        values:
                        - NEW
                        - REFURBISHED
                        - USED
                        negated: false
                    - CUSTOM_LABEL_0:
                        values:
                        - 004 - home furn leisure
                        negated: false
                    - CUSTOM_LABEL_1:
                        values:
                        - clearance
                        - original price
                        negated: false
                    - CUSTOM_LABEL_2:
                        values:
                        - 789 - table linens
                        - 794 - living room accents
                        negated: false
                    - GENDER:
                        values:
                        - FEMALE
                        - MALE
                        - UNISEX
                        negated: false
                    - ITEM_ID:
                        values:
                        - does not exists
                        - this one neither
                        - nope
                        negated: true
                    - ITEM_GROUP_ID:
                        values:
                        - nonexistant group
                        - another one
                        - last one
                        negated: true
                    - PRODUCT_TYPE_0:
                        values:
                        - - accent chairs
                          - club chairs
                        - - accent chairs
                          - slipper chairs
                        - - accent tables
                          - end tables
                        - - air mattresses
                          - air mattresses
                        - - table linens
                        negated: false
              HotelFewFiltersUsingAllOf:
                summary: A simple hotel example that applies "all of the following filters".
                description: 'The use of "all_of" creates a Product Group where all of the individual filters

                  must be satisfied by a hotel to be included in the Product Group.

                  '
                value:
                - catalog_type: HOTEL
                  name: Few Filters using "all_of"
                  catalog_id: '4866935934774'
                  filters:
                    all_of:
                    - HOTEL_ID:
                        values:
                        - hotel1
                        - hotel2
                    - CUSTOM_LABEL_1:
                        values:
                        - big_hotels
                        negated: false
      responses:
        '201':
          content:
            application/json:
              schema:
                type: array
                items:
                  description: ID of a created catalog product group.
                  example: '443727193917'
                  type: string
                  pattern: ^\d+$
          description: Success
        '400':
          description: Invalid body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                InvalidRequest:
                  value:
                    code: 1
                    message: '''feed_id'' value ''1511851494501_'' must match the pattern: ^\d+$"}'
        '401':
          description: Unauthorized access.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                UnauthorizedAccess:
                  value:
                    code: 29
                    message: You are not permitted to access that resource.
        '403':
          description: Forbidden. Account not approved for catalog product group mutations yet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                MerchantDisapproved:
                  value:
                    code: 2625
                    message: Sorry, you cannot perform this action. Account is disapproved.
                MerchantUnderReview:
                  value:
                    code: 2626
                    message: Sorry, you cannot perform this action. Account is under review.
        '409':
          description: Conflict. Can't create this catalogs product group with this value.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                CatalogsProductGroupFiltersAlreadyExist:
                  value:
                    code: 4178
                    message: A catalogs product group with these filters already exists for this feed.
                CatalogsProductGroupNameAlreadyExist:
                  value:
                    code: 4179
                    message: A catalogs product group with this name already exists for this feed.
                CatalogsMerchantNotCreated:
                  value:
                    code: 4182
                    message: Can't access this feature without an existing catalog.
                CatalogsProductGroupFiltersInvalid:
                  value:
                    code: 4183
                    message: Catalog product group filters failed validation, please ensure all filters are set correctly.
        default:
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
      - Multiple
components:
  schemas:
    GoogleProductCategory2Filter:
      type: object
      additionalProperties: false
      properties:
        GOOGLE_PRODUCT_CATEGORY_2:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - GOOGLE_PRODUCT_CATEGORY_2
    HotelIdFilter:
      type: object
      additionalProperties: false
      properties:
        HOTEL_ID:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - HOTEL_ID
    CatalogsHotelProductGroupFiltersAllOf:
      type: object
      additionalProperties: false
      properties:
        all_of:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/CatalogsHotelProductGroupFilterKeys'
      required:
      - all_of
    CatalogsProductGroupCreateRequest:
      type: object
      title: retail feed based
      description: Request object for creating a product group.
      properties:
        name:
          type: string
        description:
          type: string
          nullable: true
        is_featured:
          description: boolean indicator of whether the product group is being featured or not
          type: boolean
          default: false
        filters:
          $ref: '#/components/schemas/CatalogsProductGroupFiltersRequest'
        feed_id:
          description: Catalog Feed id pertaining to the catalog product group.
          example: '2680059592705'
          type: string
          pattern: ^\d+$
      required:
      - name
      - filters
      - feed_id
    CatalogsCreativeAssetsProductGroupFiltersAllOf:
      type: object
      additionalProperties: false
      properties:
        all_of:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/CatalogsCreativeAssetsProductGroupFilterKeys'
      required:
      - all_of
    CatalogsProductGroupMultipleMediaTypesCriteria:
      title: catalogs_product_group_multiple_media_type_criteria
      type: object
      additionalProperties: false
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/MediaType'
        negated:
          type: boolean
          default: false
      required:
      - values
    ProductType0Filter:
      type: object
      additionalProperties: false
      properties:
        PRODUCT_TYPE_0:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - PRODUCT_TYPE_0
    CatalogsHotelProductGroupFiltersAnyOf:
      type: object
      additionalProperties: false
      properties:
        any_of:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/CatalogsHotelProductGroupFilterKeys'
      required:
      - any_of
    Gender:
      type: string
      enum:
      - FEMALE
      - MALE
      - UNISEX
    ProductType3Filter:
      type: object
      additionalProperties: false
      properties:
        PRODUCT_TYPE_3:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - PRODUCT_TYPE_3
    CatalogsProductGroupMultipleCountriesCriteria:
      title: catalogs_product_group_multiple_country_criteria
      type: object
      additionalProperties: false
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/Country'
        negated:
          type: boolean
          default: false
      required:
      - values
    PriceFilter:
      type: object
      additionalProperties: false
      properties:
        PRICE:
          type: object
          additionalProperties: false
          title: catalogs_product_group_pricing_currency_criteria
          properties:
            operator:
              type: string
              enum:
              - GREATER_THAN
              - GREATER_THAN_OR_EQUALS
              - LESS_THAN
              - LESS_THAN_OR_EQUALS
            value:
              type: number
              minimum: 0
            currency:
              $ref: '#/components/schemas/NonNullableCatalogsCurrency'
            negated:
              type: boolean
              default: false
          required:
          - value
          - operator
          - currency
      required:
      - PRICE
    Error:
      title: Error
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
      - code
      - message
    CatalogsVerticalProductGroupCreateRequest:
      type: object
      title: catalog based
      description: Request object for creating a catalog based product group.
      oneOf:
      - $ref: '#/components/schemas/CatalogsRetailProductGroupCreateRequest'
      - $ref: '#/components/schemas/CatalogsHotelProductGroupCreateRequest'
      - $ref: '#/components/schemas/CatalogsCreativeAssetsProductGroupCreateRequest'
      discriminator:
        propertyName: catalog_type
        mapping:
          RETAIL: '#/components/schemas/CatalogsRetailProductGroupCreateRequest'
          HOTEL: '#/components/schemas/CatalogsHotelProductGroupCreateRequest'
          CREATIVE_ASSETS: '#/components/schemas/CatalogsCreativeAssetsProductGroupCreateRequest'
    MediaType:
      type: string
      enum:
      - IMAGE
      - VIDEO
    MaxPriceFilter:
      type: object
      additionalProperties: false
      properties:
        MAX_PRICE:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupPricingCriteria'
      required:
      - MAX_PRICE
    CatalogsProductGroupMultipleStringListCriteria:
      title: catalogs_product_group_multiple_string_list_criteria
      type: object
      additionalProperties: false
      properties:
        values:
          type: array
          items:
            type: array
            items:
              type: string
        negated:
          type: boolean
          default: false
      required:
      - values
    GoogleProductCategory5Filter:
      type: object
      additionalProperties: false
      properties:
        GOOGLE_PRODUCT_CATEGORY_5:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - GOOGLE_PRODUCT_CATEGORY_5
    CustomLabel4Filter:
      type: object
      additionalProperties: false
      properties:
        CUSTOM_LABEL_4:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - CUSTOM_LABEL_4
    CustomLabel2Filter:
      type: object
      additionalProperties: false
      properties:
        CUSTOM_LABEL_2:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - CUSTOM_LABEL_2
    GoogleProductCategory0Filter:
      type: object
      additionalProperties: false
      properties:
        GOOGLE_PRODUCT_CATEGORY_0:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - GOOGLE_PRODUCT_CATEGORY_0
    CatalogsProductGroupMultipleGenderCriteria:
      title: catalogs_product_group_multiple_gender_criteria
      type: object
      additionalProperties: false
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/Gender'
        negated:
          type: boolean
          default: false
      required:
      - values
    CatalogsProductGroupFiltersRequest:
      description: Object holding a group of filters for request on catalog product group. This is a distinct schema It is not possible to create or update a Product Group with empty filters. But some automatically generated Product Groups might have empty filters.
      title: catalogs_product_group_filters
      type: object
      anyOf:
      - type: object
        additionalProperties: false
        properties:
          any_of:
            type: array
            items:
              type: object
              $ref: '#/components/schemas/CatalogsProductGroupFilterKeys'
            minItems: 1
        required:
        - any_of
      - type: object
        additionalProperties: false
        properties:
          all_of:
            type: array
            items:
              type: object
              $ref: '#/components/schemas/CatalogsProductGroupFilterKeys'
            minItems: 1
        required:
        - all_of
    ProductType2Filter:
      type: object
      additionalProperties: false
      properties:
        PRODUCT_TYPE_2:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - PRODUCT_TYPE_2
    CatalogsHotelProductGroupFilters:
      description: Object holding a group of filters for a hotel product group
      title: catalogs_product_group_filters
      type: object
      anyOf:
      - $ref: '#/components/schemas/CatalogsHotelProductGroupFiltersAnyOf'
      - $ref: '#/components/schemas/CatalogsHotelProductGroupFiltersAllOf'
    CatalogsProductGroupMultipleStringCriteria:
      title: catalogs_product_group_multiple_string_criteria
      type: object
      additionalProperties: false
      properties:
        values:
          type: array
          items:
            type: string
        negated:
          type: boolean
          default: false
      required:
      - values
    ProductType1Filter:
      type: object
      additionalProperties: false
      properties:
        PRODUCT_TYPE_1:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - PRODUCT_TYPE_1
    CatalogsCreativeAssetsProductGroupFilters:
      description: Object holding a group of filters for a creative assets product group
      title: catalogs_product_group_filters
      type: object
      anyOf:
      - $ref: '#/components/schemas/CatalogsCreativeAssetsProductGroupFiltersAnyOf'
      - $ref: '#/components/schemas/CatalogsCreativeAssetsProductGroupFiltersAllOf'
    GoogleProductCategory3Filter:
      type: object
      additionalProperties: false
      properties:
        GOOGLE_PRODUCT_CATEGORY_3:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - GOOGLE_PRODUCT_CATEGORY_3
    CustomLabel3Filter:
      type: object
      additionalProperties: false
      properties:
        CUSTOM_LABEL_3:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - CUSTOM_LABEL_3
    CatalogsHotelProductGroupFilterKeys:
      title: catalogs_product_group_keys
      anyOf:
      - $ref: '#/components/schemas/PriceFilter'
      - $ref: '#/components/schemas/HotelIdFilter'
      - $ref: '#/components/schemas/BrandFilter'
      - $ref: '#/components/schemas/CustomLabel0Filter'
      - $ref: '#/components/schemas/CustomLabel1Filter'
      - $ref: '#/components/schemas/CustomLabel2Filter'
      - $ref: '#/components/schemas/CustomLabel3Filter'
      - $ref: '#/components/schemas/CustomLabel4Filter'
      - $ref: '#/components/schemas/CountryFilter'
    MinPriceFilter:
      type: object
      additionalProperties: false
      properties:
        MIN_PRICE:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupPricingCriteria'
      required:
      - MIN_PRICE
    CatalogsProductGroupPricingCriteria:
      title: catalogs_product_group_pricing_criteria
      type: object
      additionalProperties: false
      properties:
        inclusion:
          type: boolean
          default: true
        values:
          type: number
          minimum: 0
        negated:
          type: boolean
          default: false
      required:
      - values
    GoogleProductCategory1Filter:
      type: object
      additionalProperties: false
      properties:
        GOOGLE_PRODUCT_CATEGORY_1:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - GOOGLE_PRODUCT_CATEGORY_1
    CreativeAssetsIdFilter:
      type: object
      additionalProperties: false
      properties:
        CREATIVE_ASSETS_ID:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - CREATIVE_ASSETS_ID
    ConditionFilter:
      type: object
      additionalProperties: false
      properties:
        CONDITION:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - CONDITION
    GenderFilter:
      type: object
      additionalProperties: false
      properties:
        GENDER:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleGenderCriteria'
      required:
      - GENDER
    CatalogsLocale:
      type: string
      enum:
      - af-ZA
      - ar-SA
      - bg-BG
      - bn-IN
      - cs-CZ
      - da-DK
      - de
      - el-GR
      - en-AU
      - en-CA
      - en-GB
      - en-IN
      - en-US
      - es-419
      - es-AR
      - es-ES
      - es-MX
      - fi-FI
      - fr
      - fr-CA
      - he-IL
      - hi-IN
      - hr-HR
      - hu-HU
      - id-ID
      - it
      - ja
      - ko-KR
      - ms-MY
      - nb-NO
      - nl
      - pl-PL
      - pt-BR
      - pt-PT
      - ro-RO
      - ru-RU
      - sk-SK
      - sv-SE
      - te-IN
      - th-TH
      - tl-PH
      - tr
      - uk-UA
      - vi-VN
      - zh-CN
      - zh-TW
    AvailabilityFilter:
      type: object
      additionalProperties: false
      properties:
        AVAILABILITY:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - AVAILABILITY
    ItemGroupIdFilter:
      type: object
      additionalProperties: false
      properties:
        ITEM_GROUP_ID:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - ITEM_GROUP_ID
    CatalogsProductGroupCurrencyCriteria:
      title: catalogs_product_group_currency_criteria
      type: object
      description: A currency filter. This filter cannot be negated
      additionalProperties: false
      properties:
        values:
          $ref: '#/components/schemas/NonNullableCatalogsCurrency'
        negated:
          type: boolean
          default: false
          enum:
          - false
      required:
      - values
    CatalogsCreativeAssetsProductGroupCreateRequest:
      type: object
      title: creative_assets_product_groups_create_request
      additionalProperties: false
      description: Request object for creating a creative assets product group.
      properties:
        catalog_type:
          type: string
          enum:
          - CREATIVE_ASSETS
        name:
          type: string
        description:
          type: string
          nullable: true
        filters:
          $ref: '#/components/schemas/CatalogsCreativeAssetsProductGroupFilters'
        catalog_id:
          description: Catalog id pertaining to the creative assets product group.
          example: '2680059592705'
          type: string
          pattern: ^\d+$
      required:
      - name
      - filters
      - catalog_id
      - catalog_type
    GoogleProductCategory4Filter:
      type: object
      additionalProperties: false
      properties:
        GOOGLE_PRODUCT_CATEGORY_4:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - GOOGLE_PRODUCT_CATEGORY_4
    ItemIdFilter:
      type: object
      additionalProperties: false
      properties:
        ITEM_ID:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - ITEM_ID
    NonNullableCatalogsCurrency:
      type: string
      description: Currency Codes from ISO 4217.
      nullable: false
      example: USD
      enum:
      - AED
      - AFN
      - ALL
      - AMD
      - ANG
      - AOA
      - ARS
      - AUD
      - AWG
      - AZN
      - BAM
      - BBD
      - BDT
      - BGN
      - BHD
      - BIF
      - BMD
      - BND
      - BOB
      - BRL
      - BSD
      - BTN
      - BWP
      - BYN
      - BYR
      - BZD
      - CAD
      - CDF
      - CHF
      - CLP
      - CNY
      - COP
      - CRC
      - CUC
      - CUP
      - CVE
      - CZK
      - DJF
      - DKK
      - DOP
      - DZD
      - EGP
      - ERN
      - ETB
      - EUR
      - FJD
      - FKP
      - GBP
      - GEL
      - GGP
      - GHS
      - GIP
      - GMD
      - GNF
      - GTQ
      - GYD
      - HKD
      - HNL
      - HRK
      - HTG
      - HUF
      - IDR
      - ILS
      - IMP
      - INR
      - IQD
      - IRR
      - ISK
      - JEP
      - JMD
      - JOD
      - JPY
      - KES
      - KGS
      - KHR
      - KMF
      - KPW
      - KRW
      - KWD
      - KYD
      - KZT
      - LAK
      - LBP
      - LKR
      - LRD
      - LSL
      - LYD
      - MAD
      - MDL
      - MGA
      - MKD
      - MMK
      - MNT
      - MOP
      - MRO
      - MUR
      - MVR
      - MWK
      - MXN
      - MYR
      - MZN
      - NAD
      - NGN
      - NIO
      - NOK
      - NPR
      - NZD
      - OMR
      - PAB
      - PEN
      - PGK
      - PHP
      - PKR
      - PLN
      - PYG
      - QAR
      - RON
      - RSD
      - RUB
      - RWF
      - SAR
      - SBD
      - SCR
      - SDG
      - SEK
      - SGD
      - SHP
      - SLL
      - SOS
      - SPL
      - SRD
      - STD
      - SVC
      - SYP
      - SZL
      - THB
      - TJS
      - TMT
      - TND
      - TOP
      - TRY
      - TTD
      - TVD
      - TWD
      - TZS
      - UAH
      - UGX
      - USD
      - UYU
      - UZS
      - VEF
      - VND
      - VUV
      - WST
      - XAF
      - XCD
      - XDR
      - XOF
      - XPF
      - YER
      - ZAR
      - ZMW
      - ZWD
    CustomLabel1Filter:
      type: object
      additionalProperties: false
      properties:
        CUSTOM_LABEL_1:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - CUSTOM_LABEL_1
    CatalogsCreativeAssetsProductGroupFiltersAnyOf:
      type: object
      additionalProperties: false
      properties:
        any_of:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/CatalogsCreativeAssetsProductGroupFilterKeys'
      required:
      - any_of
    CatalogsRetailProductGroupCreateRequest:
      type: object
      title: retail_product_groups_create_request
      additionalProperties: false
      description: Request object for creating a product group.
      properties:
        catalog_type:
          type: string
          enum:
          - RETAIL
          description: Retail catalog based product group is available only for selected partners at the moment. If you are not eligible, please use feed based one.
        name:
          type: string
        description:
          type: string
          nullable: true
        filters:
          $ref: '#/components/schemas/CatalogsProductGroupFiltersRequest'
        catalog_id:
          description: Catalog id pertaining to the retail product group.
          example: '2680059592705'
          type: string
          pattern: ^\d+$
        country:
          $ref: '#/components/schemas/Country'
        locale:
          $ref: '#/components/schemas/CatalogsLocale'
      required:
      - name
      - filters
      - catalog_id
      - catalog_type
      - country
      - locale
    Country:
      type: string
      description: Country ID from ISO 3166-1 alpha-2.
      example: US
      enum:
      - AD
      - AE
      - AF
      - AG
      - AI
      - AL
      - AM
      - AO
      - AQ
      - AR
      - AS
      - AT
      - AU
      - AW
      - AX
      - AZ
      - BA
      - BB
      - BD
      - BE
      - BF
      - BG
      - BH
      - BI
      - BJ
      - BL
      - BM
      - BN
      - BO
      - BQ
      - BR
      - BS
      - BT
      - BV
      - BW
      - BY
      - BZ
      - CA
      - CC
      - CD
      - CF
      - CG
      - CH
      - CI
      - CK
      - CL
      - CM
      - CN
      - CO
      - CR
      - CU
      - CV
      - CW
      - CX
      - CY
      - CZ
      - DE
      - DJ
      - DK
      - DM
      - DO
      - DZ
      - EC
      - EE
      - EG
      - EH
      - ER
      - ES
      - ET
      - FI
      - FJ
      - FK
      - FM
      - FO
      - FR
      - GA
      - GB
      - GD
      - GE
      - GF
      - GG
      - GH
      - GI
      - GL
      - GM
      - GN
      - GP
      - GQ
      - GR
      - GS
      - GT
      - GU
      - GW
      - GY
      - HK
      - HM
      - HN
      - HR
      - HT
      - HU
      - ID
      - IE
      - IL
      - IM
      - IN
      - IO
      - IQ
      - IR
      - IS
      - IT
      - JE
      - JM
      - JO
      - JP
      - KE
      - KG
      - KH
      - KI
      - KM
      - KN
      - KR
      - KW
      - KY
      - KZ
      - LA
      - LB
      - LC
      - LI
      - LK
      - LR
      - LS
      - LT
      - LU
      - LV
      - LY
      - MA
      - MC
      - MD
      - ME
      - MF
      - MG
      - MH
      - MK
      - ML
      - MM
      - MN
      - MO
      - MP
      - MQ
      - MR
      - MS
      - MT
      - MU
      - MV
      - MW
      - MX
      - MY
      - MZ
      - NA
      - NC
      - NE
      - NF
      - NG
      - NI
      - NL
      - 'NO'
      - NP
      - NR
      - NU
      - NZ
      - OM
      - PA
      - PE
      - PF
      - PG
      - PH
      - PK
      - PL
      - PM
      - PN
      - PR
      - PS
      - PT
      - PW
      - PY
      - QA
      - RE
      - RO
      - RS
      - RU
      - RW
      - SA
      - SB
      - SC
      - SD
      - SE
      - SG
      - SH
      - SI
      - SJ
      - SK
      - SL
      - SM
      - SN
      - SO
      - SR
      - SS
      - ST
      - SV
      - SX
      - SY
      - SZ
      - TC
      - TD
      - TF
      - TG
      - TH
      - TJ
      - TK
      - TL
      - TM
      - TN
      - TO
      - TR
      - TT
      - TV
      - TW
      - TZ
      - UA
      - UG
      - UM
      - US
      - UY
      - UZ
      - VA
      - VC
      - VE
      - VG
      - VI
      - VN
      - VU
      - WF
      - WS
      - YE
      - YT
      - ZA
      - ZM
      - ZW
    CatalogsProductGroupFilterKeys:
      title: catalogs_product_group_keys
      anyOf:
      - $ref: '#/components/schemas/MinPriceFilter'
      - $ref: '#/components/schemas/MaxPriceFilter'
      - $ref: '#/components/schemas/CurrencyFilter'
      - $ref: '#/components/schemas/ItemIdFilter'
      - $ref: '#/components/schemas/AvailabilityFilter'
      - $ref: '#/components/schemas/BrandFilter'
      - $ref: '#/components/schemas/ConditionFilter'
      - $ref: '#/components/schemas/CustomLabel0Filter'
      - $ref: '#/components/schemas/CustomLabel1Filter'
      - $ref: '#/components/schemas/CustomLabel2Filter'
      - $ref: '#/components/schemas/CustomLabel3Filter'
      - $ref: '#/components/schemas/CustomLabel4Filter'
      - $ref: '#/components/schemas/ItemGroupIdFilter'
      - $ref: '#/components/schemas/GenderFilter'
      - $ref: '#/components/schemas/ProductType4Filter'
      - $ref: '#/components/schemas/ProductType3Filter'
      - $ref: '#/components/schemas/ProductType2Filter'
      - $ref: '#/components/schemas/ProductType1Filter'
      - $ref: '#/components/schemas/ProductType0Filter'
      - $ref: '#/components/schemas/GoogleProductCategory6Filter'
      - $ref: '#/components/schemas/GoogleProductCategory5Filter'
      - $ref: '#/components/schemas/GoogleProductCategory4Filter'
      - $ref: '#/components/schemas/GoogleProductCategory3Filter'
      - $ref: '#/components/schemas/GoogleProductCategory2Filter'
      - $ref: '#/components/schemas/GoogleProductCategory1Filter'
      - $ref: '#/components/schemas/GoogleProductCategory0Filter'
      - $ref: '#/components/schemas/ProductGroupReferenceFilter'
    MediaTypeFilter:
      type: object
      additionalProperties: false
      properties:
        MEDIA_TYPE:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleMediaTypesCriteria'
      required:
      - MEDIA_TYPE
    ProductType4Filter:
      type: object
      additionalProperties: false
      properties:
        PRODUCT_TYPE_4:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - PRODUCT_TYPE_4
    CurrencyFilter:
      type: object
      additionalProperties: false
      properties:
        CURRENCY:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupCurrencyCriteria'
      required:
      - CURRENCY
    CatalogsHotelProductGroupCreateRequest:
      type: object
      title: hotel_product_groups_create_request
      additionalProperties: false
      description: Request object for creating a hotel product group.
      properties:
        catalog_type:
          type: string
          enum:
          - HOTEL
        name:
          type: string
        description:
          type: string
          nullable: true
        filters:
          $ref: '#/components/schemas/CatalogsHotelProductGroupFilters'
        catalog_id:
          description: Catalog id pertaining to the hotel product group.
          example: '2680059592705'
          type: string
          pattern: ^\d+$
      required:
      - name
      - filters
      - catalog_id
      - catalog_type
    ProductGroupReferenceFilter:
      type: object
      additionalProperties: false
      properties:
        PRODUCT_GROUP:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - PRODUCT_GROUP
    GoogleProductCategory6Filter:
      type: object
      additionalProperties: false
      properties:
        GOOGLE_PRODUCT_CATEGORY_6:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringListCriteria'
      required:
      - GOOGLE_PRODUCT_CATEGORY_6
    BrandFilter:
      type: object
      additionalProperties: false
      properties:
        BRAND:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - BRAND
    CatalogsCreativeAssetsProductGroupFilterKeys:
      title: catalogs_product_group_keys
      anyOf:
      - $ref: '#/components/schemas/CreativeAssetsIdFilter'
      - $ref: '#/components/schemas/CustomLabel0Filter'
      - $ref: '#/components/schemas/CustomLabel1Filter'
      - $ref: '#/components/schemas/CustomLabel2Filter'
      - $ref: '#/components/schemas/CustomLabel3Filter'
      - $ref: '#/components/schemas/CustomLabel4Filter'
      - $ref: '#/components/schemas/GoogleProductCategory6Filter'
      - $ref: '#/components/schemas/GoogleProductCategory5Filter'
      - $ref: '#/components/schemas/GoogleProductCategory4Filter'
      - $ref: '#/components/schemas/GoogleProductCategory3Filter'
      - $ref: '#/components/schemas/GoogleProductCategory2Filter'
      - $ref: '#/components/schemas/GoogleProductCategory1Filter'
      - $ref: '#/components/schemas/GoogleProductCategory0Filter'
      - $ref: '#/components/schemas/MediaTypeFilter'
    CustomLabel0Filter:
      type: object
      additionalProperties: false
      properties:
        CUSTOM_LABEL_0:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleStringCriteria'
      required:
      - CUSTOM_LABEL_0
    CountryFilter:
      type: object
      additionalProperties: false
      properties:
        COUNTRY:
          type: object
          $ref: '#/components/schemas/CatalogsProductGroupMultipleCountriesCriteria'
      required:
      - COUNTRY
  parameters:
    query_ad_account_id:
      name: ad_account_id
      description: Unique identifier of an ad account.
      in: query
      schema:
        type: string
        pattern: ^\d+$
        maxLength: 18
    query_catalogs_product_group_ids_required:
      name: id
      in: query
      style: form
      explode: false
      description: Comma-separated list of product group ids
      required: true
      schema:
        type: array
        items:
          type: integer
        minItems: 1
        maxItems: 1000
  securitySchemes:
    pinterest_oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://www.pinterest.com/oauth/
          tokenUrl: https://api.pinterest.com/v5/oauth/token
          scopes:
            ads:read: See all of your advertising data, including ads, ad groups, campaigns etc.
            ads:write: Create, update, or delete ads, ad groups, campaigns etc.
            billing:read: See all of your billing data, billing profile, etc.
            billing:write: Create, update, or delete billing data, billing profiles, etc.
            biz_access:read: See business access data
            biz_access:write: Create, update, or delete business access data
            boards:read: See your public boards, including group boards you join
            boards:read_secret: See your secret boards
            boards:write: Create, update, or delete your public boards
            boards:write_secret: Create, update, or delete your secret boards
            catalogs:read: See all of your catalogs data
            catalogs:write: Create, update, or delete your catalogs data
            pins:read: See your public Pins
            pins:read_secret: See your secret Pins
            pins:write: Create, update, or delete your public Pins
            pins:write_secret: Create, update, or delete your secret Pins
            user_accounts:read: See your user accounts and followers
            user_accounts:write: Update your user accounts and followers
    conversion_token:
      type: http
      scheme: bearer
      description: This security scheme only applies to the conversion events endpoint (POST /ad_accounts/{ad_account_id}/events). This endpoint requires a bearer token generated via Ads Manager (ads.pinterest.com).
    basic:
      type: http
      scheme: basic
x-tagGroups:
- name: Pin and Boards
  tags:
  - pins
  - boards
  - media
  - aggregated_comments
  - aggregated_pin_data
  - user_account
- name: Campaign Management
  tags:
  - ad_accounts
  - campaigns
  - ad_groups
  - ads
  - product_group_promotions
  - bulk
- name: Targeting
  tags:
  - audiences
  - customer_lists
  - keywords
  - targeting_template
  - audience_insights
  - audience_sharing
- name: Ad Formats
  tags:
  - lead_forms
  - lead_ads
  - leads_export
- name: Billing
  tags:
  - billing
  - order_lines
  - terms_of_service
- name: Business Access
  tags:
  - business_access_assets
  - business_access_invite
  - business_access_relationships
- name: Conversions
  tags:
  - conversion_events
  - conversion_tags
- name: Others
  tags:
  - integrations
  - oauth
  - resources
  - search
  - terms
- name: Shopping
  tags:
  - catalogs
- name: Deprecated
  tags:
  - product_groups
